# Generated by Django 4.0 on 2021-12-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosaz_todoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='text',
            field=models.TextField(default='', verbose_name='متن'),
            preserve_default=False,
        ),
    ]
