# Generated by Django 4.0 on 2022-01-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todosaz_todoes', '0002_todo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
    ]
