# Generated by Django 3.2.11 on 2022-01-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todosaz_todoes', '0003_alter_todo_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='simple_desc',
        ),
    ]
