# Generated by Django 3.2.11 on 2022-01-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todosaz_todoes', '0004_remove_todo_simple_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_active',
        ),
    ]
