# Generated by Django 3.2.11 on 2022-01-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todosaz_news', '0002_new_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='new',
            name='short_desc',
        ),
    ]
