# Generated by Django 4.0 on 2021-12-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('short_desc', models.CharField(max_length=120, verbose_name='توضیحات کوتاه')),
                ('about', models.TextField(verbose_name='درباره')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل پشتیبانی')),
                ('phone', models.CharField(max_length=50, verbose_name='تلفن تماس')),
            ],
            options={
                'verbose_name': 'تنظیم',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
